### ISSUE TITLE
Provide a way to define regexes

### ISSUE THREAD

**Issue by mallowigi** [ziolko/intellij-javascript-symbols#2]
I wonder if that would be possible to add a setting to define the regexes of symbols, for instance '@@symbol'.

Thank you, great plugin!

**Comment by ziolko** [comment]
Great idea. I will take a look at this in my leisure time and hopefully in a week it will be released.
I will let you know about progress on Wednesday.

Have a nice day,
Mateusz

**Comment by ziolko** [comment]
Hi @mallowigi,

Sorry for this radio silence. I didn't have time yet to work on this topic, but I will take a look at this very soon :)

Mateusz

**Comment by mallowigi** [comment]
Don't feel obligated man! Whenever you want!

**Comment by ziolko** [comment]
Hi @mallowigi,

I've just released a new version supporting configuration of symbol RegExp. You will find it in the "Other Settings" section of IntelliJ IDEA (it is not documented yet). Please let me know if it works well for you :)

Have a nice day,
Mateusz
